/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<string, string, string>;

export interface Collaborators {
  area: string | null;
  birth_date: string | null;
  cpf: string | null;
  created_at: Generated<Timestamp>;
  disability: string | null;
  education_level: string | null;
  email: string | null;
  employment_type: string | null;
  /**
   * Valores de colunas customizadas do CSV do cliente, escolhidas como filtro/demográfico na criação do mapeamento, chaveadas pelo slug do cabeçalho (ver src/lib/mapping/column-key.ts).
   */
  extra_fields: Generated<Json>;
  gender: string | null;
  has_answered: Generated<boolean>;
  id: Generated<string>;
  mapping_id: string | null;
  marital_status: string | null;
  name: string | null;
  organization: string | null;
  race_color: string | null;
  remote_status: string | null;
  role: string | null;
  updated_at: Generated<Timestamp>;
  which_disability: string | null;
}

export interface Managers {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  password_hash: string;
  role: Generated<string>;
  temp_password_plain: string | null;
}

export interface MappingManagers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  manager_id: string;
  mapping_id: string;
  role: Generated<string>;
}

export interface Mappings {
  config: Json | null;
  created_at: Generated<Timestamp>;
  csv_columns: Json | null;
  description: string | null;
  id: Generated<string>;
  is_demo: Generated<boolean>;
  module_type: string | null;
  name: string;
  slug: string;
  status: Generated<string>;
  tcle_text: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Responses {
  answers: Json | null;
  collaborator_id: string;
  completion_percent: Numeric | null;
  created_at: Generated<Timestamp>;
  hse_class: string | null;
  hse_domains: Json | null;
  hse_score: Numeric | null;
  id: Generated<string>;
  job_observations: string | null;
  /**
   * Respostas brutas dos 73 campos do módulo Saúde Mental, chaveadas pelo nome do campo (ver src/lib/analytics/mental-health-definition.ts). Fonte da verdade: tudo o mais é derivado daqui.
   */
  mental_health_answers: Json | null;
  /**
   * Classificação do índice: Insatisfatório (<5), Regular (<7), Bom (<9), Excelente (>=9) ou Sem dados.
   */
  mental_health_class: string | null;
  /**
   * Cache do resultado de calculateMentalHealth(): componentes com nota/peso, níveis, categorias e flags descritivas. Recalculável a partir de mental_health_answers.
   */
  mental_health_derived: Json | null;
  /**
   * Índice de Saúde Mental (0–10; 0–5 quando há indicador de risco de suicídio, pois o divisor vira 2). NULL quando a soma dos pesos respondidos fica abaixo do piso de confiabilidade.
   */
  mental_health_score: Numeric | null;
  remote_class: string | null;
  remote_domains: Json | null;
  remote_score: Numeric | null;
  submitted_at: Generated<Timestamp>;
}

export interface TenantManagers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  manager_id: string;
  role: Generated<string>;
  tenant_id: string;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  slug: string;
}

export interface DB {
  collaborators: Collaborators;
  managers: Managers;
  mapping_managers: MappingManagers;
  mappings: Mappings;
  responses: Responses;
  tenant_managers: TenantManagers;
  tenants: Tenants;
}
